# @package _global_

model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 0.001
    dt_max: 0.1
    conj_sym: true
    clip_eigs: false
  ssm:
    discretization: async
    d_model: 256
    d_ssm: 256
    ssm_block_size: 16
    num_stages: 2
    num_layers_per_stage: 6
    dropout: 0.3
    classification_mode: timepool
    prenorm: true
    batchnorm: true
    bn_momentum: 0.95
    pooling_stride: 8
    pooling_mode: timepool
    state_expansion_factor: 2
