# @package _global_

model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 0.005
    dt_max: 0.1
    conj_sym: true
    clip_eigs: false
  ssm:
    discretization: zoh
    d_model: 32
    d_ssm: 32
    ssm_block_size: 4
    num_stages: 1
    num_layers_per_stage: 4
    dropout: 0.27
    classification_mode: timepool
    prenorm: true
    batchnorm: true
    bn_momentum: 0.95
    pooling_stride: 1
    pooling_mode: avgpool
    state_expansion_factor: 1
