# @package _global_

model:
  ssm_init:
    C_init: lecun_normal
    dt_min: 0.001
    dt_max: 0.1
    conj_sym: true
    clip_eigs: false
  ssm:
    discretization: state_zoh
    discretization_first_layer: state_zoh
    d_model: 512
    d_ssm: 512
    block_size: 16
    num_layers: 12
    activation_fn: half_glu2
    dropout: 0.1
    classification_mode: timepool
    prenorm: true
    batchnorm: true
    bn_momentum: 0.95
    pooling_stride: 8
    pooling_every_n_layers: 4
    pooling_mode: timepool
    state_expansion_factor: 2
