# @package _global_
defaults:
  - /model: audio/medium

task:
  name: ssc-classification

training:
  num_epochs: 30
  per_device_batch_size: 64
  per_device_eval_batch_size: 128
  num_workers: 6
  time_jitter: 900
  noise: 35
  drop_event: 0.1
  time_skew: 1.12
  pad_unit: 8192

optimizer:
  ssm_lr: 1e-3
  lr_factor: 4
  warmup_epochs: 3
  ssm_weight_decay: 0.0
  weight_decay: 1e-2
  schedule: cosine