# @package _global_
defaults:
  - /model: audio/medium

task:
  name: ssc-classification

training:
  num_epochs: 100
  per_device_batch_size: 64
  per_device_eval_batch_size: 128
  num_workers: 6
  time_jitter: 1
  spatial_jitter: 1.0
  noise: 100
  drop_event: 0.1
  max_drop_chunk: 0.1
  time_skew: 1.05
  pad_unit: 8192

optimizer:
  ssm_base_lr: 1e-5
  lr_factor: 4
  warmup_epochs: 10
  ssm_weight_decay: 0.0
  weight_decay: 5e-2
  schedule: cosine
  accumulation_steps: 1