defaults:
  - _self_
  - system: local
  - task: spiking-heidelberg-digits
  - logging: local

#seed: 1234
seed: 1200
#seed: 1100
#seed: 1000
#seed: 900

hydra:
  run:
    dir: ${output_dir}/hydra-outputs/${now:%Y-%m-%d-%H-%M-%S}
